{"path":null,"line":null,"char":null,"code":"NEWLINE","severity":"error","name":"Linter failed","description":"Linter failed. This a bug, please file an issue against the linter maintainer.\n\nCONTEXT:\nLinter command failed with non-zero exit code.\nSTDERR:\n<MainThread:DEBUG> Checking file /Volumes/Source/pytorch/pytorch_copy_2/test\nTraceback (most recent call last):\n  File \"/Volumes/Source/pytorch/pytorch_copy_2/tools/linter/adapters/newlines_linter.py\", line 158, in <module>\n    lint_message = check_file(filename)\n  File \"/Volumes/Source/pytorch/pytorch_copy_2/tools/linter/adapters/newlines_linter.py\", line 39, in check_file\n    with open(filename, \"rb\") as f:\nIsADirectoryError: [Errno 21] Is a directory: '/Volumes/Source/pytorch/pytorch_copy_2/test'\n\n\nSTDOUT:\n"}
{"path":"/Volumes/Source/pytorch/pytorch_copy_2/test","line":null,"char":null,"code":"EXEC","severity":"error","name":"executable-permissions","description":"This file has executable permission; please remove it by using `chmod -x`."}
